### PR TITLE
[SM Image] Move Pytorch to 2.3.0 and DGL to 2.3.0

### PR DESCRIPTION
**Pull request by jalencato**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zhjwy9343** [comment]
Is this image tested on SageMaker environment?

**Comment by jalencato** [comment]
> Is this image tested on SageMaker environment?

I am running some internal tests now but not finished yet. Should be ready this afternoon.

**Review by zhjwy9343 — APPROVED** [review]
If past our SM test, LGTM.

**Comment by jalencato** [comment]
> > Is this image tested on SageMaker environment?
> 
> I am running some internal tests now but not finished yet. Should be ready this afternoon.

I am waiting for one job here for partition. Currently because of instance availability problem.

**Pull request merged**
